INFO_SEEDS/empleado/applications/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="home_app" 

urlpatterns=[
    path(
        'panel/',
        views.HomePage.as_view(),
        name='panel',
    ),

    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    
    path(
        'servicios/',
        views.ServiciosView.as_view(),
        name='servicios'
    ),
    path(
        'equipo/',
        views.EquipoView.as_view(),
        name='equipo'
    ),
    path(
        'contactanos/',
        views.ContactanosView.as_view(),
        name='contactanos'
    ),
    path(
        'ingresar/',
        views.IngresarView.as_view(),
        name='ingresar'
    ),
    path('prueba/',views.PruebaView.as_view()),
    path('lista/',views.PruebaListView.as_view()),
    path('lista-prueba/',views.ListarPrueba.as_view()),
    path('add/',views.PruebaCreateView.as_view(),name='prueba_add'),
    #submétodo as_view: indica que estamos ejecut una vista genérica
    path(
        'resume-foundation/',
        views.ResumeFoundationView.as_view(),
        name='resume_foundation'
    ),
]

INFO_SEEDS/empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static #ayudara a generar urls estáticas de nuestros archivos multimedia

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.users.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
                                #en base a esta config nos genere una url para la ruta de un 
                                #documento guardado en nuestro documento 

INFO_SEEDS/empleado/applications/home/models.py
from django.db import models

# Create your models here.
class Prueba(models.Model):
    titulo = models.CharField(max_length=100)
    subtitulo = models.CharField(max_length=50)
    cantidad = models.IntegerField()

    def __str__(self):  #me ofrece retornar una variable
        return self.titulo+' - '+self.subtitulo

INFO_SEEDS/empleado/applications/home/forms.py
#Acá escribiré las personalizaciones para los campos
from django import forms #paquete interno que me ayuda a crear formularios
from .models import Prueba

class PruebaForm(forms.ModelForm):
    class Meta:
        model=Prueba
        #fields=('__all__')
        fields=(
            'titulo',
            'subtitulo',
            'cantidad',
        )
        widgets={
            'titulo':forms.TextInput(
                attrs={
                    'placeholder':'Ingrese texto aquí'
                }
            )
        }
    '''
    def clean_cantidad(self):  #a la altura de class xq estamos escrib un metodo para prueba form
        cantidad = self.cleaned_data['cantidad'] #recupero lo que se escribe en cantidad
        if cantidad<10:
            raise forms.ValidationError('Ingrese un numero mayor a 10')

        return cantidad
    '''

INFO_SEEDS/empleado/applications/home/views.py
from django.shortcuts import render

# Create your views here.
#from django.views.generic import TemplateView, ListView, CreateView
from django.views.generic import (
    TemplateView, 
    ListView, 
    CreateView
)
# Import models
from .models import Prueba 
from .forms import PruebaForm  #para el model form parte1


class HomePage(TemplateView): #agregado
    template_name='home/index.html'

class InicioView(TemplateView):
    template_name='iniciohome.html'
'''
class NosotrosView(TemplateView):
    template_name='home/nosotroshome.html'
'''
class ServiciosView(TemplateView):
    template_name='home/servicioshome.html'

class EquipoView(TemplateView):
    template_name='home/equipohome.html'

class ContactanosView(TemplateView):
    template_name='home/contactanoshome.html'

class IngresarView(TemplateView):
    template_name='home/ingresarhome.html'

class PruebaView(TemplateView):
    template_name='home/prueba.html'

class ResumeFoundationView(TemplateView):
    template_name='home/resume_foundation.html'


class PruebaListView(ListView):     #PruebaListVies es una lista genérica
    template_name = 'home/lista.html'
    context_object_name='listaNumeros'
    queryset=['5','10','15']     #no solo pueden ser así, sino registros de una BD.


class ListarPrueba(ListView):   #El listview heredo de la vista genérica. 
                                #interpreta que quiero listar todo o que tenga el modelo prueba. 
    template_name = "home/lista_prueba.html"  #ubicación
    model=Prueba
    context_object_name='lista'  #accedemos al resultado de listar de tabla prueba.


class PruebaCreateView(CreateView):         #formulario
    template_name = "home/add.html"
    model=Prueba
    #fields=['titulo','subtitulo','cantidad']
    form_class=PruebaForm
    success_url='/' #Al copletarse el proceso va a la pagina principal o de inicio 

    

INFO_SEEDS/empleado/templates/base.html
{% load static %}   <!--indicamos que usaremos los archivos estáticos de DJ-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>{% block title %}{% endblock title %}</title> <!--todo templates trabajaran bajo foundation-->
</head>
<body>
    {% block content %}{% endblock content %}
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
      $(document).foundation();
    </script>
</body>
</html>

INFO_SEEDS/empleado/templates/basehome.html
{% load static %}   <!--indicamos que usaremos los archivos estáticos de DJ-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>{% block title %}{% endblock title %}</title> <!--todo templates trabajaran bajo foundation-->
</head>
<body>
    {% block content %}{% endblock content %}
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
      $(document).foundation();
    </script>
</body>
</html>

INFO_SEEDS/empleado/templates/home/add.html
<h2>Prueba de createview</h2>
<!--<input type="text" placeholder="Ingrese titulo">-->
<form method="POST">{% csrf_token %}
    {{form.as_p}}
    <button type="submit">Guardar</button>
</form>

<!--
<label for="prueba">prueba:</label>
<input type="text" placeholder="Ingrese texto aquí">
-->

INFO_SEEDS/empleado/templates/home/contactanoshome.html
{% extends 'basehome.html' %}

{% block title %} Pagina de inicio SERVIPAC{% endblock title %}


{% block content %}

{% include 'includes/headerhome.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/estilos.css' %}" />
<link rel="stylesheet" href="{% static 'css/responsive.css' %}" />



<section class=" " id="contactanos_container">
    <div class="row align-items-center caja_contacto ">
        <h2 id="contactanos" class="titulo ">Sign up, and we will give you 1 free consultation with a specialist!</h2>
        <div class="caja__contacto">
            <div class="contactar col-4 col-md-6 col-sm-12 ">
                <form>
                    <div class="form-group espaci ">
                        <label for="exampleFormControlInput1 ">Name and surname</label>
                        <input type="text " class="form-control " onkeypress="return letra(event)" placeholder="NAME AND SURNAME " required>
                    </div>
                    <div class="form-group espaci ">
                        <label for="exampleFormControlInput1 ">MAIL</label>
                        <input type="email " class="form-control " id="exampleFormControlInput1 " placeholder="EMAIL " required>
                    </div>
                    <div class="form-group espaci ">
                        <label for="exampleFormControlInput1 ">
                            TELEPHONE
                    </label>
                        <input type="text " class="form-control " onkeypress="return numeros(event)" placeholder="PHONE " required>
                    </div>
                    <div class="form-group espaci ">
                        <label for="exampleFormControlTextarea1 ">
                            MESSAGE OR INQUIRY
                    </label>
                        <textarea class="form-control " id="exampleFormControlTextarea1 " rows="3 " required>
                    </textarea>
                    </div>
                    <button type="submit " class="btn btn-primary col-lg-12 col-xl-2 mt-2">REGISTER</button>

                </form>
            </div>
            <div class=" col-4 col-md-6 col-sm-12 caja-mapa">
                <div class="mapa ">
                    <a href="https://goo.gl/maps/GQybnVEtwnMT8EH56 ">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d316798.0246286718!2d-106.30112119784259!3d28.684957532562283!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86ea449d5d484033%3A0xb7f1a7a706dd1d7b!2sChihuahua%2C%20Chih.%2C%20M%C3%A9xico!5e0!3m2!1ses-419!2spe!4v1633286201759!5m2!1ses-419!2spe" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                            
                    </a>
                </div>

                <div class="location-container container-sm border row align-items-center ">
                    <div class=" col-3 ">
                        <div class="location ">
                            <div class="location-icon ">
                                <i class="bi bi-cursor-fill "></i>
                            </div>
                        </div>
                    </div>
                    <div class="col ">
                        <p class="my-1 ">Location</p>
                        <p class="my-1 ">Chihuahua-Mexico</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% include 'includes/footerhome.html' %}

{% endblock content %}

INFO_SEEDS/empleado/templates/home/equipohome.html
{% extends 'basehome.html' %}

{% block title %} Pagina de inicio SERVIPAC{% endblock title %}


{% block content %}

{% include 'includes/headerhome.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/equipo.css' %}" >
    <title></title>
</head>

<body>
    <div class="equipo">
        <div class="texto">
            <h1>Our Team</h1>
            <p>Our Team is made up of students and professionals from Mexico and Peru who are experts on the subject.</p>
        </div>
        <div class="imagenes">
            <div class="trabajadores">
                <img src="{% static 'images/Richard Nope.png' %}" alt="">
                <div class="descripcion">
                    <h2>Richard Ñope</h2>
                    <p>
                        Programmer-researcher
                    </p>
                </div>
            </div>
            <div class="trabajadores">
                <img src="{% static 'images/Ana Miriam.jpeg' %}" alt="">
                <div class="descripcion">
                    <h2>Ana Miriam</h2>
                    <p>
                        Programmer-researcher
                    </p>
                </div>
            </div>
            <div class="trabajadores">
                <img src="{% static 'images/Julio Diaz.png' %}"  alt="">
                <div class="descripcion">
                    <h2>Julio Diaz</h2>
                    <p>
                        Artificial intelligence
                    </p>
                </div>
            </div>
            <div class="trabajadores">
                <img src="{% static 'images/Maria Carmona.png' %}" alt="">
                <div class="descripcion">
                    <h2>Maria Carmona</h2>
                    <p>
                        Management-research
                    </p>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

{% include 'includes/footerhome.html' %}

{% endblock content %}

INFO_SEEDS/empleado/templates/home/home2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>Titutlo de la pagina</title>
</head>

<header style="border:solid red;height: 40px;">
    <a href="">opcion uno</a>
    <a href="">opcion dos</a>
    <a href="">opcion tres</a>
</header>

<body>
    <h1>Resumen Foundation</h1>
    <div class="grid-x" style="border: 1px solid green;">
        <h2 class="cell small-12 large-5" style="border: 1px solid red;">elemento 1</h2>
        <h2 class="cell large-4">elemento 2</h2>
        <h2 class="cell large-3" style="border: 1px solid red;">elemento 3</h2>
        <div class="cell large-4 grid-x" style="border: 1px solid yellow;">
            <h4 class="cell large-2">otro elemento 1</h4>
            <h4 class="cell large-2">otro elemento 2</h4>
            <h4>otro elemento 3</h4>
        </div>
    </div>
</body>
</html>

INFO_SEEDS/empleado/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Panel de usuario</h1>
    <h3>Bienvenido: {{user}}</h3>
    <ul>
        <li><a href="{% url 'users_app:user-logout' %}">Cerrar sesion</a></li>
        <li><a href="#">Actualizar datos</a></li>
    </ul>
</body>
</html>

INFO_SEEDS/empleado/templates/home/ingresarhome.html
{% extends 'basehome.html' %}

{% block title %} Pagina de inicio SERVIPAC{% endblock title %}


{% block content %}

{% include 'includes/headerhome.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script
      src="https://kit.fontawesome.com/64d58efce2.js"
    ></script>
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <title>LOGIN SERVIPAC</title>
  </head>
  <body>
    <div class="container">
      <div class="forms-container">
        <div class="signin-signup">
          <form action="#" class="sign-in-form">
            <h2 class="title">LOG IN</h2>
            

            <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
              <div class="grid-container">
                <div class="grid-x grid-padding-x">
                  
                  <div class="medium-12 cell">
                    <label>User
                      <input type="text" placeholder="USER">
                    </label>
                    <label>password
                      <input type="text" placeholder="PASSWORD">
                    </label>
                    
                    <button type="submit" class="button">LOG IN</button>
                  </div>
                  
                </div>
                <p class="social-text">ENTER WITH ANOTHER PLATFORM</p>
              </div>
            </form>

            <div class="social-media">
              <a href="#" class="social-icon">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-google"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </div>
        </div>
      </div>

      <div class="panels-container">
        <div class="panel left-panel">
          <div class="content">
            <h3>Any questions?</h3>
            <p>
              Contact technical support infoseedssoporte@infoseeds.com.pe
            </p>
            <i class="fas fa-envelope"></i>
          </div>
          <img src="{% static 'images/Logo_Info_Seeds.png' %}" alt="">
          
        </div>
      </div>
      
    </div>

    <script src="{% static 'js/app.js' %}"></script>
  </body>

</html>

{% endblock content %}

INFO_SEEDS/empleado/templates/home/iniciohome.html
{% extends 'basehome.html' %}

INFO_SEEDS/empleado/templates/home/lista.html
<h1>Prueba de ListView</h1>

{{listaNumeros}}

INFO_SEEDS/empleado/templates/home/lista_prueba.html
<h1>Lista prueba listview</h1>


{% for elemento in lista %} <!--elemento: lo que quiero iterar
                            lista: en el que quiero iterar ese elem.-->
    <p>
        {{elemento.cantidad}}-{{elemento.titulo}}  <!--cantidad. titulo.-->
    </p>
{% endfor %}
    
<!--{{lista}}-->

INFO_SEEDS/empleado/templates/home/nosotroshome.html
{% extends 'basehome.html' %}

{% block title %} Pagina de inicio SERVIPAC{% endblock title %}


{% block content %}

{% include 'includes/headerhome.html' %}
{% load static %}

<h1>soy la parte nosotros</h1>
{% endblock content %}

INFO_SEEDS/empleado/templates/home/prueba.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!--<link rel="stylesheet" href="{% static 'css/prueba.css' %}">-->
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
</head>
<body>
    <h1 class="ejemplo1">Hola mundo desde los nuevos templates</h1>
    <h2 class="ejemplo2">Cargando estilos</h2>
    
    <!-- Anchors (links) -->
    <a href="about.html" class="button">Learn More</a>
    <a href="#features" class="button">View All Features</a>

    <!-- Buttons (actions) -->
    <button type="button" class="success button">Save</button>
    <button type="button" class="alert button">Delete</button>
    
</body>
</html>

INFO_SEEDS/empleado/templates/home/resume_foundation.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>Document</title>
</head>
<body>
    <h1>Resumen Foundation</h1>
    <div class="grid-x" style="border: 1px solid green;">
        <h2 class="cell small-12 large-5" style="border: 1px solid red;">elemento 1</h2>
        <h2 class="cell large-4">elemento 2</h2>
        <h2 class="cell large-3" style="border: 1px solid red;">elemento 3</h2>
        <div class="cell large-4 grid-x" style="border: 1px solid yellow;">
            <h4 class="cell large-2">otro elemento 1</h4>
            <h4 class="cell large-2">otro elemento 2</h4>
            <h4>otro elemento 3</h4>
        </div>
    </div>
</body>
</html>

INFO_SEEDS/empleado/templates/home/servicioshome.html
{% extends 'basehome.html' %}

{% block title %} Pagina de inicio SERVIPAC{% endblock title %}


{% block content %}

{% include 'includes/headerhome.html' %}
{% load static %}
  


  <link rel="stylesheet" href="{% static 'css/estilos2.css' %}" />
 
    <div class="servicios">
      <div class="servicios__items">
        <div class="items">
          <div class="items_img">
            <img src="{% static 'images/Estudio_Terreno.jpg' %}"  alt="" />
        
          </div>
          <div class="items_textos">
            <h2>STUDY OF THE LAND FOR PLANTING</h2>
            <p>
              You will be able to know if the chosen land is suitable for sowing a certain plant
            </p>
          </div>
        </div>
        <div class="items">
          <div class="items_img">
            <img src="{% static 'images/Metereologia.jpg' %}"  alt="" />
          </div>
          <div class="items_textos">
            <h2>MEASUREMENT OF WEATHER VARIABLES</h2>
            <p>
              In this way you will be able to know the climate of the land where you have your plantations
            </p>
          </div>
        </div>
        <div class="items">
          <div class="items_img">
            <img src="{% static 'images/Plagas.jpg' %}"  alt="" />
             
          </div>
          <div class="items_textos">
            <h2>PEST DETECTION</h2>
            <p>
              You will be able to detect the pests present in your plants, we only need you to specify the 
              place where your crop is located
            </p>
          </div>
        </div>
        
          
        <div class="items">
          <div class="items_img">
            <img src="{% static 'images/Humedad.png' %}" alt="" />
        
          </div>
          <div class="items_textos">
            <h2>HUMIDITY OF FLOOR</h2>
            <p>
              You will be able to know the level of humidity of the soil in order to know the amount of water 
              necessary for the irrigation of your crops
            </p>
          </div>
        </div>

        
      </div>
    </div>




<!--Inicio de la imagen de portada-->
<!--eliminado-->
<!--Fin de la imagen de portada-->

{% include 'includes/footerhome.html' %}

{% endblock content %}

INFO_SEEDS/empleado/templates/includes/header.html
{% load static %}

<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>

        <div class="top-bar-left">
          <ul class="menu">
            <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
            <li><img src="{% static 'images/logo.png' %}" alt="  " width="100"></li> 
                    <!--redirecciona a añadir empleado-->
          </ul>
        </div>

        <!--
        <li><a href="{% url 'persona_app:empleado_add' %}" class="button">Registrar nuevo</a></li> 
        <li>
          <img src="{% static 'images/logo.png' %}" alt="  " width="100">
        <li class="menu-text"></li><img src="{ %  static 'images/logo.jpg' %}"/></li>  <--comentado estaba
        </li>
        -->
        <li>
          <a href="{% url 'persona_app:empleados_all' %}"><h4>Listar</h4></a>
        </li>

        <li><a href="{% url 'departamento_app:departamento_list' %}"><h4>Departamento</h4></a></li> 
                              <!--error si no declaro nombre a las url de app depart-->
        <li><a href="{% url 'persona_app:empleados_admin' %}"><h4>Administrar</h4></a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}"><h4>Nuevo departamento</h4></a></li>
      </ul>
    </div>


    <div class="top-bar-right">
      <ul class="menu">
        <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
        <li><a href="{% url 'persona_app:empleado_add' %}" class="hollow button"  href="#"><h5>Registrar nuevo</h5></a></li> 
                <!--redirecciona a añadir empleado-->
      </ul>
    </div>

    <div class="top-bar-right">
      <ul class="menu">
        <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
        <li><a href="{% url 'home_app:ingresar' %}" class="hollow button alert" href="#"><h5>Salir</h5></a></li> 
                <!--redirecciona a añadir empleado-->
      </ul>
    </div>
  </div>

INFO_SEEDS/empleado/templates/includes/headerhome.html
{% load static %}

<!--
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>

        <div class="top-bar-left">
          <ul class="menu">
          -->
            <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
<!--            <li><img src="{% static 'images/logo.png' %}" alt="  " width="100"></li>  -->
                    <!--redirecciona a añadir empleado-->
<!--          </ul>
        </div>

        <li><a href="{% url 'home_app:inicio' %}"><h4>INICIO</h4></a></li>
        
        <li><a href="{% url 'home_app:servicios' %}"><h4>SERVICIOS</h4></a></li>
        
        <li><a href="{% url 'home_app:equipo' %}"><h4>EQUIPO</h4></a></li>
        
        <li><a href="{% url 'home_app:contactanos' %}"><h4>CONTÁCTANOS</h4></a></li>
        
      </ul>
    </div>
  

    <div class="top-bar-right">
      <ul class="menu"> -->
        <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
<!--        <li><a href="{% url 'home_app:ingresar' %}" class="button"><h5>INGRESAR</h5></a></li> -->
                <!--redirecciona a añadir empleado-->
<!--      </ul>
    </div>
  </div>
-->
<!--
<nav id="menu" class="navbar  sticky-top navbar-expand-lg navbar-light bg-light">
  <div class="container-lg">
    <a class="navbar-brand  " href="#">
        <img class="img-fluid rounded float-start" src="{% static 'images/logo.png' %}" alt="" width="80" height="50" />
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarsExample09">
      <ul class="navbar-nav nav nav-pills">
        
          
          <li class="nav-item ">
              <a class="nav-link" href="{% url 'home_app:inicio' %}">INICIO</a>
          </li>
        
          <li class="nav-item">
              <a class="nav-link" href="{% url 'home_app:servicios' %}">SERVICIOS</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'home_app:equipo' %}">EQUIPO</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'home_app:contactanos' %}">CONTÁCTANOS</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link"  href="{% url 'home_app:ingresar' %}" class="button">INGRESAR</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
-->


<div class="top-bar sticky-top ">
  <div class="top-bar-left">
    
    <ul class="dropdown menu" data-dropdown-menu>

      <div class="top-bar-left">
        <ul class="menu">
          <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
           <li><img src="{% static 'images/Logo_Info_Seeds.png' %}" alt="  " width="120"></li>  
                  <!--redirecciona a añadir empleado-->
        </ul>
      </div>

      <li><a href="{% url 'home_app:inicio' %}">HOME</a></li>
      
      <li><a href="{% url 'home_app:servicios' %}">SERVICES</a></li>
      
      <li><a href="{% url 'home_app:equipo' %}">TEAM</a></li>
      
      <li><a href="{% url 'home_app:contactanos' %}">CONTACT US</a></li>
      
    </ul>
  </div>


  <div class="top-bar-right">
    <ul class="menu">
      <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
      <li><a href="{% url 'home_app:ingresar' %}" class="button"><h5>LOG IN</h5></a></li> 
              <!--redirecciona a añadir empleado-->
    </ul>
  </div>
</div>